ALIAS_PATH="$ZSH_CUSTOM/aliases.zsh"
UTIL_PATH="$ZSH_CUSTOM/util.zsh"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
RESET="\033[0m" # Resets the text to default color
export BROWSER_NAME="Firefox"

alias aggd='agg -v --font-family "MesloLGS NF" --theme "monokai"'
alias asp=". aws-set-profile"
# alias assume="awsume"
alias aws-check="(aws sts get-caller-identity > /dev/null 2>&1 && echo -e '${GREEN}Authenticated') || echo -e '${RED}Not Authenticated'"
alias back=". cd -2"
alias bi="brew update && brew install"
alias branch="git checkout -b"
alias browser="open -a '$BROWSER_NAME'"
alias bu="brew update && brew upgrade"
alias bun="brew uninstall"
alias cat="bat"
alias cb="cargo build"
alias cbr="cargo build && cargo run"
alias cbw="cargo watch -x run"
alias cd="z"
alias cdaurora="cd $HOME/work/aurora-playground"
alias cdcustom=". cd $ZSH_CUSTOM"
alias cdplat="cd-iac-platform"
alias cdproj="cd-iac-project"
alias cdrepos=". cd $HOME/work"
alias cdsbx=". cd $HOME/work/mk-int-sbx-liamgraham"
alias chat='python ~/bin/chatgpt-cli/chatgpt.py'
alias clusters='list-eks-clusters'
alias cm="clone-me"
alias co="code ."
alias commit="git-smart-commit"
alias cr="cargo run"
alias cw="clone-work"
alias edit-aliases="vim $ALIAS_PATH && source $ALIAS_PATH"
alias edit-util="vim $UTIL_PATH && source $UTIL_PATH"
alias envoy="parse-envoy | jq"
alias fgc='fzf-git-checkout'
alias force-push="git push --force"
alias fp="git push --force"
alias gadc="gcloud auth application-default login"
alias gamend="git commit --amend --no-edit"
alias gauth="gcloud auth login"
alias gca="gcloud-activate"
alias gcd="gcloud config configurations activate default"
alias gda="git-all-diffs"
alias ggc='grep-git-checkout'
alias gpo='git pull origin main'
alias gistc='gh gist clone' 
alias gistl='gh gist list'
alias git-amend="git commit --amend --no-edit"
alias glc="git log --pretty=format:%s | fzf | pbcopy"
alias gll='git log --decorate --format="%C(auto)%h %ad %C(green)%an%C(auto)%d %C(reset)%s" --date=format:"%Y-%m-%d %H:%M"'
alias gs="git status"
alias gtoken="gcloud auth print-access-token | tee >(pbcopy)"
alias instances="AWS_PAGER=\"\" aws ec2 describe-instances --filters \"Name=instance-state-name,Values=running\" --query 'Reservations[*].Instances[*].[Tags[?Key==\`Name\`] | [0].Value, InstanceId][] | sort_by(@, &[0])' --output table"
alias ip="ipconfig getifaddr en0"
alias jira="open -a \"Google Chrome\" \"https://workcoverqld.atlassian.net/jira/software/c/projects/CLOUD/boards/886?assignee=712020%3A4d66770f-538d-42ed-a501-57080975b850\""
alias jn='jira issue list -q "assignee = currentUser() AND sprint in openSprints() and status != Done" --order-by "status" --reverse'
alias jnp='jn --plain'
alias jwt-decode='pbpaste | xargs jwt decode'
alias k8s='open-k8s-dashboard'
alias kiali-token='kubectl -n istio-system create token kiali'
alias main="git checkout main"
alias nbuild="npm run build"
alias nbust="npm run build && npm run start"
alias nbute="npm run build && npm run test -- --coverage"
alias ndev="npm run dev"
alias ni="npm install"
alias nid="npm install --save-dev"
alias nigl="npm install --global"
alias nlint="npm run lint"
alias nout="npm outdated"
alias nstart="npm run start"
alias ntest="npm run test -- --coverage"
alias nuni="npm uninstall"
alias nupd="npm update"
alias npm-public="[ ! -f .npmrc ] && echo 'registry=https://registry.npmjs.org' > .npmrc || rich -p '[red].npmrc already exists'" 
alias p="pnpm"
alias pdc="pdc -sdkpath /Users/liamgraham/Developer/PlaydateSDK"
alias pi="pnpm install"
alias prun="poetry run python"
alias raspberry="ssh raspberry@192.168.68.64"
alias rename="git-edit-branch"
alias repo='gh browse'
alias repoc='gh browse -b $(git branch --show-current)'
alias restart="exec zsh"
alias richp="rich --print --emoji"
alias stash-pull="git stash && git pull && git stash pop"
alias ssm="start-ssm-session"
alias sso="aws-sso-util login"
alias target="set-target-cluster"
alias td="tilt down"
alias tg="terragrunt"
alias tga='terragrunt apply -parallelism 20 -auto-approve tg.plan'
alias tgaa='terragrunt apply -parallelism 20 -auto-approve'
alias tgp='terragrunt plan -parallelism 20 -out tg.plan'
alias tu="tilt up"
alias utc="date -u +"%Y-%m-%dT%H:%M:%SZ""
alias undo="git reset --soft HEAD~1"
alias vercel="open-vercel-dashboard"
alias vim="nvim" 
alias yadd="yarn add"
alias yi="yarn install"
